a.append("turtle")
a=[ ]
a.append("red")
a.append("yellow")
a.append("green")
t. goto(100,200)
t.color(a[0])
t.stamp()
t.goto(-100,-200)
t.color(a[1])
t.stamp()
t.goto(-200, 0)
t.color(a[2])
t.stamp()
