Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> a=15
>>> b=5
>>> print('a='a,a'b=,b)
...       
SyntaxError: unterminated string literal (detected at line 1)
>>> print('a='a,a,'b=',b)
...       
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> print('a=',a,a,'b=',b)
...       
a= 15 15 b= 5
>>> c=a
...       
>>> a=b
...       
>>> b=c
...       
>>> print('a=','b=',b)
...       
a= b= 15
